CREATE TABLE IF NOT EXISTS BOARDS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TITLE TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS CARDS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    BOARD_ID INTEGER REFERENCES BOARD(BOARD_ID),
    TITLE TEXT NOT NULL
);